.TH GO-JO 1 "January 2025" "go-jo" "User Commands"
.SH NAME
go-jo \- print the current version of go-jo
.SH SYNOPSIS
.B go-jo
.SH DESCRIPTION
.B go-jo
is a simple GoLang application that prints its current version, git commit, and build date.
.SH OPTIONS
This command takes no options.
.SH EXAMPLES
.TP
.B go-jo
Print the current version information
.SH AUTHOR
Henrique Ferreira (henrique.ferreira@unvoid.com)
.SH SEE ALSO
For more information, visit: https://github.com/henrique-ferreira-unvoid/go-jo 