name: Release Installer

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to release (e.g., v1.2.3)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        default: false
        type: boolean

jobs:
  release-installer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build go-jo-integration-installer
      run: |
        echo "Building go-jo-integration-installer for version ${{ inputs.version }}"
        
        # Create output directory
        mkdir -p dist/installer
        
        # Build the binary
        go build -o dist/installer/go-jo-integration-installer ./apps/go-jo-integration-installer
        
        # Create a tar.gz archive
        cd dist/installer
        tar -czf go-jo-integration-installer_${{ inputs.version }}_linux_amd64.tar.gz go-jo-integration-installer
        
        # Create checksum file
        sha256sum go-jo-integration-installer_${{ inputs.version }}_linux_amd64.tar.gz > checksums.txt
        
        echo "Build completed successfully"

    - name: Upload installer artifacts
      uses: actions/upload-artifact@v4
      with:
        name: go-jo-installer-artifacts
        path: |
          dist/installer/go-jo-integration-installer
          dist/installer/go-jo-integration-installer_*_linux_amd64.tar.gz
          dist/installer/checksums.txt
        retention-days: 1 